import {
	GatewayNoBodyRequestSchema,
	GatewayUnknownResponseSchema,
	LoreDetailSchema,
	LoreFormSchema,
	LoreListResponseSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleCreateLore,
	handleDeleteLore,
	handleGetLore,
	handleListLore,
	handleUpdateLore,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const LORE_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/lore",
		handler: handleListLore,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: LoreListResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/lore/{lore_id}",
		handler: handleGetLore,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: LoreDetailSchema,
	},
	{
		method: "POST",
		pattern: "/v1/lore",
		handler: handleCreateLore,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: LoreFormSchema,
		responseSchema: LoreDetailSchema,
	},
	{
		method: "PUT",
		pattern: "/v1/lore/{lore_id}",
		handler: handleUpdateLore,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: LoreFormSchema,
		responseSchema: LoreDetailSchema,
	},
	{
		method: "DELETE",
		pattern: "/v1/lore/{lore_id}",
		handler: handleDeleteLore,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
];
