import {
	CoreMemoryBlockListSchema,
	CoreMemoryBlockSchema,
	EpisodeListSchema,
	GatewayNoBodyRequestSchema,
	NarrativeListSchema,
	PinnedSummaryListSchema,
	SettlementListSchema,
	UnresolvedWorldStateOpsListSchema,
	WorldStateEdgesListSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleAgentMemoryEpisodes,
	handleAgentMemoryNarratives,
	handleAgentMemorySettlements,
	handleAgentMemoryUnresolvedWorldStateOps,
	handleAgentMemoryWorldStateEdges,
	handleGetCoreMemoryBlock,
	handleListCoreMemoryBlocks,
	handleListPinnedSummaries,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const MEMORY_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/episodes",
		handler: handleAgentMemoryEpisodes,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: EpisodeListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/narratives",
		handler: handleAgentMemoryNarratives,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: NarrativeListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/settlements",
		handler: handleAgentMemorySettlements,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: SettlementListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/core-blocks",
		handler: handleListCoreMemoryBlocks,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: CoreMemoryBlockListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/core-blocks/{label}",
		handler: handleGetCoreMemoryBlock,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: CoreMemoryBlockSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/pinned-summaries",
		handler: handleListPinnedSummaries,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: PinnedSummaryListSchema,
	},
	// World-state debug surface for the frontend Study Room. The two routes
	// expose the same data Talker sees in [world_state] retrieval (active
	// fact_edges anchored on an entity) plus the unresolved replay queue so a
	// developer can trace why a worldStateOp didn't materialize.
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/world-state",
		handler: handleAgentMemoryWorldStateEdges,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: WorldStateEdgesListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/world-state/unresolved-ops",
		handler: handleAgentMemoryUnresolvedWorldStateOps,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: UnresolvedWorldStateOpsListSchema,
	},
];
