import {
	CoreMemoryBlockListSchema,
	CoreMemoryBlockSchema,
	EpisodeListSchema,
	GatewayNoBodyRequestSchema,
	NarrativeListSchema,
	PinnedSummaryListSchema,
	SettlementListSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleAgentMemoryEpisodes,
	handleAgentMemoryNarratives,
	handleAgentMemorySettlements,
	handleGetCoreMemoryBlock,
	handleListCoreMemoryBlocks,
	handleListPinnedSummaries,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const MEMORY_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/episodes",
		handler: handleAgentMemoryEpisodes,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: EpisodeListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/narratives",
		handler: handleAgentMemoryNarratives,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: NarrativeListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/settlements",
		handler: handleAgentMemorySettlements,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: SettlementListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/core-blocks",
		handler: handleListCoreMemoryBlocks,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: CoreMemoryBlockListSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/core-blocks/{label}",
		handler: handleGetCoreMemoryBlock,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: CoreMemoryBlockSchema,
	},
	{
		method: "GET",
		pattern: "/v1/agents/{agent_id}/memory/pinned-summaries",
		handler: handleListPinnedSummaries,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: PinnedSummaryListSchema,
	},
];
