import {
	GatewayNoBodyRequestSchema,
	GatewayUnknownResponseSchema,
	PersonaDetailSchema,
	PersonaFormSchema,
	PersonaListResponseSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleCreatePersona,
	handleDeletePersona,
	handleGetPersona,
	handleListPersonas,
	handleReloadPersonas,
	handleUpdatePersona,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const PERSONA_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/personas",
		handler: handleListPersonas,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: PersonaListResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/personas/{id}",
		handler: handleGetPersona,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: PersonaDetailSchema,
	},
	{
		method: "POST",
		pattern: "/v1/personas",
		handler: handleCreatePersona,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: PersonaFormSchema,
		responseSchema: PersonaDetailSchema,
	},
	{
		method: "PUT",
		pattern: "/v1/personas/{id}",
		handler: handleUpdatePersona,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: PersonaFormSchema,
		responseSchema: PersonaDetailSchema,
	},
	{
		method: "DELETE",
		pattern: "/v1/personas/{id}",
		handler: handleDeletePersona,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "POST",
		pattern: "/v1/personas:reload",
		handler: handleReloadPersonas,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
];
