import {
	GatewayNoBodyRequestSchema,
	GatewayUnknownResponseSchema,
	RetrievalTraceSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleLogs,
	handleRequestChunks,
	handleRequestDiagnose,
	handleRequestPrompt,
	handleRequestRetrievalTrace,
	handleRequestSummary,
	handleRequestTrace,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const REQUEST_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/summary",
		handler: handleRequestSummary,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/prompt",
		handler: handleRequestPrompt,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/chunks",
		handler: handleRequestChunks,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/diagnose",
		handler: handleRequestDiagnose,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/trace",
		handler: handleRequestTrace,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/requests/{request_id}/retrieval-trace",
		handler: handleRequestRetrievalTrace,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: true,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: RetrievalTraceSchema,
	},
	{
		method: "GET",
		pattern: "/v1/logs",
		handler: handleLogs,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
];
