import {
	GatewayNoBodyRequestSchema,
	GatewayUnknownResponseSchema,
	SessionCloseResponseSchema,
	SessionCreateRequestSchema,
	SessionCreateResponseSchema,
	SessionListResponseSchema,
	SessionRecoverRequestSchema,
	SessionRecoverResponseSchema,
	TurnStreamRequestSchema,
} from "../../contracts/cockpit/browser.js";
import {
	handleCloseSession,
	handleCreateSession,
	handleListSessions,
	handleRecoverSession,
	handleSessionMemory,
	handleSessionTranscript,
	handleTurnStream,
} from "../controllers.js";
import type { RouteEntry } from "../route-definition.js";

export const SESSION_ROUTES: RouteEntry[] = [
	{
		method: "GET",
		pattern: "/v1/sessions",
		handler: handleListSessions,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: SessionListResponseSchema,
	},
	{
		method: "POST",
		pattern: "/v1/sessions",
		handler: handleCreateSession,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: SessionCreateRequestSchema,
		responseSchema: SessionCreateResponseSchema,
	},
	{
		method: "POST",
		pattern: "/v1/sessions/{session_id}/turns:stream",
		handler: handleTurnStream,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "sse",
		requestSchema: TurnStreamRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "POST",
		pattern: "/v1/sessions/{session_id}/close",
		handler: handleCloseSession,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: SessionCloseResponseSchema,
	},
	{
		method: "POST",
		pattern: "/v1/sessions/{session_id}/recover",
		handler: handleRecoverSession,
		scope: "write",
		audit: true,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: SessionRecoverRequestSchema,
		responseSchema: SessionRecoverResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/sessions/{session_id}/transcript",
		handler: handleSessionTranscript,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
	{
		method: "GET",
		pattern: "/v1/sessions/{session_id}/memory",
		handler: handleSessionMemory,
		scope: "read",
		audit: false,
		cors: true,
		pgRequired: false,
		errorTransport: "json",
		requestSchema: GatewayNoBodyRequestSchema,
		responseSchema: GatewayUnknownResponseSchema,
	},
];
